### ISSUE TITLE
unsup_loss_ca always equals 0.0051, is that correct?

### ISSUE THREAD

**Issue by machengcheng2016** [NJUyued/RDA4RobustSSL#2]
unsup_loss_ca always equals 0.0051, from beginning to end. Is that normal?
![image](https://github.com/NJUyued/RDA4RobustSSL/assets/22851860/df03ab0a-acbe-41f4-afec-e84fd027e4ae)

**Comment by NJUyued** [comment]
Hi @machengcheng2016 ，
Thank you for your comment. Based on our own experiments, we have observed that unsup_loss_ca does vary to some extent, but this variation is relatively small. It could be due to the nature of the complementary labels and our reversed operation. It is possible that you obtained the observed results on CIFAR-10, where the variation in unsup_loss_ca tends to be less pronounced than on other more diffcult datasets.
